CREATE TABLE CLIENT_MASTER  (
CLIENTNO varchar(6) PRIMARY KEY,
NAME varchar(20) not null,
ADDRESS1 varchar(30),
ADDRESS2 varchar(30),
CITY varchar(15),
PINCODE numeric(8),
STATE varchar(15),
BALDUE numeric(10,2)
);

INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C0001','Ivan Bayross','Mumbai',400054,'Maharashtra',15000);
INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C0005','Rahul','Kerala',500087,'Chennai',10000);
INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C00075','Shyam','Gavi',500087,'Kerala',60000);


SELECT*FROM CLIENT_MASTER;
--DROP TABLE CLIENT_MASTER;
SELECT NAME FROM CLIENT_MASTER;
SELECT * FROM CLIENT_MASTER WHERE CITY='Mumbai';
SELECT NAME,CITY,STATE FROM CLIENT_MASTER WHERE NOT STATE ='Maharashtra';
SELECT * FROM CLIENT_MASTER where ClientNo in('C0001', 'C0002');
DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C0005';
SELECT * FROM CLIENT_MASTER WHERE CITY Like '_a%';
ALTER TABLE CLIENT_MASTER ADD Phone_no VARCHAR(20);
ALTER TABLE CLIENT_MASTER ALTER COLUMN NAME VARCHAR(60);
ALTER TABLE CLIENT_MASTER drop COLUMN pincode;

SELECT*FROM CLIENT_MASTER;
JOIN 


CREATE TABLE PRODUCT_MASTER(
PRODUCTNO varchar(6) PRIMARY KEY,
DESCRIPTION varchar(15) not null,
PROFITPERC numeric(4,2) not null,
UNITMEASURE varchar(10) not null,
QTYONHAND numeric(8)not null,
REORDERLVL numeric(8) not null,
SELLPRICE numeric(8,2) not null,
COSTPRICE numeric(8,2) not null
);
Insert into PRODUCT_MASTER VALUES('P00001','T-Shirts',5,'piece',200,50,350,250);
Insert into PRODUCT_MASTER VALUES('P00004','Kurthi',7,'piece',100,80,4150,350);
Insert into PRODUCT_MASTER VALUES('P00003','jeans',4,'piece',600,60,550,150);
SELECT*FROM PRODUCT_MASTER;
SELECT *FROM PRODUCT_MASTER WHERE SELLPRICE BETWEEN 2000 AND 5000;
UPDATE Product_Master SET SELLPRICE='550'where SELLPRICE='350';
SELECT COUNT(*)AS NUMBER FROM PRODUCT_MASTER WHERE SELLPRICE>=1500;


CREATE TABLE SALESMAN_MASTER(
SALESMANNO varchar(6) Primary key,
SALESMANNAME varchar(20) not null,
ADDRESS1 varchar(30) not null,
ADDRESS2 varchar(30),
CITY numeric(8),
PINCODE numeric(8),
State VARCHAR(20),
SALAMT numeric(8,2) not null,
TGTTOGET numeric(6,2) not null,
YTDSALES numeric(6,2) not null,
REMARKS varchar(60)
);
insert into SALESMAN_MASTER values('s00001','Aman','A/14','Worli','Mumbai',400002,'Maharashtra',3000,100,50,'Good')
insert into SALESMAN_MASTER values('s00002','Ram','A/8','Tom','Mumbai',400001,'Maharashtra',2000,100,50,'Good')
insert into SALESMAN_MASTER values('s00003','Hari','A/5','Jerry','Mumbai',400003,'Maharashtra',4000,100,50,'Good');

CREATE TABLE SALES_ORDER(
ORDERNO varchar(6) PRIMARY KEY
CLIENTNO varchar(6) FOREIGN KEY references CLIENT_MASTER,
ORDERDATE date,
DELYADDR varchar(25),
SALESMANNO varchar(6) FOREIGN KEY references SALESMAN_MASTER,
DELYTYPE char(1) Check  (DELYTYPE ='P' OR DELYTYPE = 'S'),
BILLEDYN char(1) Check  (BILLEDYN ='y' OR BILLEDYN = 'n'),
DELYDATE date,
ORDERSTATUS varchar(20) Check(ORDERSTATUS='in process' or ORDERSTATUS='fulfilled' or ORDERSTATUS='backorder'or ORDERSTATUS= 'cancelled')
);
INSERT INTO SALES_ORDER(OrderNo,OrderDate,ClientNo,DelyType,Billedyn,SalesmanNo,DelyDate,Orderstatus)VALUES('019001','12-JUNE-02','C00001','p','s','S00001','20-JULY-02','In Process');
INSERT INTO SALES_ORDER(OrderNo,OrderDate,ClientNo,DelyType,Billedyn,SalesmanNo,DelyDate,Orderstatus)VALUES('019002','2-JUNE-02','C00002','y','n','S00002','28-JULY-02','In Cancelled');
INSERT INTO SALES_ORDER(OrderNo,OrderDate,ClientNo,DelyType,Billedyn,SalesmanNo,DelyDate,Orderstatus)VALUES('019003','6-JUNE-02','C00003','p','y','S00003','3-JULY-02','Fullfilled');

CREATE TABLE SALES_ORDER_DETAILS(
ORDERNO varchar(6) FOREIGN KEY to SALES_ORDER,
PRODUCTNO varchar(6) Foreign Key to PRODUCT_MASTER,
QTYORDERED numeric(8),
QTYDISP NUMERIC(8),
PRODUCTRATE numeric(10,2) Create Composite PRIMARY KEY of ORDERNO and PRODUCTNO);

INSERT INTO SALES_ORDER_DETAILS (ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)VALUES('019001','P00001',4,4,525);
INSERT INTO SALES_ORDER_DETAILS (ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)VALUES('019001','P00003',3,2,525);
INSERT INTO SALES_ORDER_DETAILS (ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)VALUES('019003','P00005',3,1,525);
INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C0001','Ivan Bayross','Mumbai',400054,'Maharashtra',15000);
INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C0005','Rahul','Kerala',500087,'Chennai',10000);
INSERT INTO CLIENT_MASTER  (ClientNo,Name,City,PinCode,State,BalDue)VALUES('C00075','Shyam','Gavi',500087,'Kerala',60000);


SELECT*FROM CLIENT_MASTER;
--DROP TABLE CLIENT_MASTER;
SELECT NAME FROM CLIENT_MASTER;
SELECT * FROM CLIENT_MASTER WHERE CITY='Mumbai';
SELECT NAME,CITY,STATE FROM CLIENT_MASTER WHERE NOT STATE ='Maharashtra';
SELECT * FROM CLIENT_MASTER where ClientNo in('C0001', 'C0002');
DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C0005';
SELECT * FROM CLIENT_MASTER WHERE CITY Like '_a%';
ALTER TABLE CLIENT_MASTER ADD Phone_no VARCHAR(20);
ALTER TABLE CLIENT_MASTER ALTER COLUMN NAME VARCHAR(60);
ALTER TABLE CLIENT_MASTER drop COLUMN pincode;







select * from SALES_ORDER;