//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MASTER
    {
        public string PRODUCTNO { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PROFITPERC { get; set; }
        public string UNITMEASURE { get; set; }
        public decimal QTYONHAND { get; set; }
        public decimal REORDERLVL { get; set; }
        public decimal SELLPRICE { get; set; }
        public decimal COSTPRICE { get; set; }
    }
}
