//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string studentID { get; set; }
        public string studentname { get; set; }
        public int age { get; set; }
        public string place { get; set; }
        public Nullable<int> contact { get; set; }
    }
}
